/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package easylife.EasyLifeUI;

import com.raven.main.Main;
import java.awt.Color;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

public class MyCart extends javax.swing.JFrame {

    private int userId;
    private dbConnection connect;

    /**
     * Creates new form MyCart
     */
    public MyCart() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        init();

        connect = new dbConnection(); // Instantiate the dbConnection class

        if (connect == null) {
            System.out.println("Error in connection. Can't connect to the database");
        } else {
            System.out.println("Connection successful");
        }
    }

    private void init() {
        winButton.initEvent(this, background1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new com.raven.swing.Background();
        header = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jlabelLoginLogo = new javax.swing.JLabel();
        winButton = new com.raven.swing.win_button.WinButton();
        jPanel1 = new javax.swing.JPanel();
        jbDeleteAllProducts = new javax.swing.JButton();
        jbDeleteProduct = new javax.swing.JButton();
        jbShowProducts = new javax.swing.JButton();
        jbAddProduct = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header.setBackground(new java.awt.Color(29, 101, 166));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 161, 4));
        jLabel7.setText("<html>  <h1>My Cart</h1> </html>");

        jlabelLoginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easylife/img/EasyLife-logo.jpg"))); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(winButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                .addComponent(jlabelLoginLogo))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addComponent(winButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelLoginLogo)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1.setOpaque(false);

        jbDeleteAllProducts.setBackground(new java.awt.Color(204, 204, 255));
        jbDeleteAllProducts.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbDeleteAllProducts.setForeground(new java.awt.Color(29, 101, 166));
        jbDeleteAllProducts.setText("Delete All");
        jbDeleteAllProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbDeleteAllProductsMouseClicked(evt);
            }
        });
        jbDeleteAllProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteAllProductsActionPerformed(evt);
            }
        });

        jbDeleteProduct.setBackground(new java.awt.Color(204, 204, 255));
        jbDeleteProduct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbDeleteProduct.setForeground(new java.awt.Color(29, 101, 166));
        jbDeleteProduct.setText("Delete Product");
        jbDeleteProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbDeleteProductMouseClicked(evt);
            }
        });
        jbDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeleteProductActionPerformed(evt);
            }
        });

        jbShowProducts.setBackground(new java.awt.Color(204, 204, 255));
        jbShowProducts.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbShowProducts.setForeground(new java.awt.Color(29, 101, 166));
        jbShowProducts.setText("Show Product");
        jbShowProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbShowProductsMouseClicked(evt);
            }
        });
        jbShowProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbShowProductsActionPerformed(evt);
            }
        });

        jbAddProduct.setBackground(new java.awt.Color(204, 204, 255));
        jbAddProduct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbAddProduct.setForeground(new java.awt.Color(29, 101, 166));
        jbAddProduct.setText("Add Product");
        jbAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAddProductMouseClicked(evt);
            }
        });
        jbAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddProductActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(29, 101, 166));
        jButton5.setText("To DashBoard");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbAddProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jbDeleteProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jbDeleteAllProducts, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jbShowProducts, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jbShowProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbDeleteAllProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Brand", "Description"
            }
        ));
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbDeleteProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDeleteProductMouseClicked
        String con = "jdbc:mysql://localhost:3306/easylife";
        String username = "root";
        String password = "";
        DefaultTableModel delete = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            String selected = jTable1.getValueAt(selectedRow, 0).toString();
            delete.removeRow(selectedRow);
            try (Connection conn = DriverManager.getConnection(con, username, password)) {
                PreparedStatement ps = conn.prepareStatement("DELETE FROM product WHERE item = ?");
                ps.setString(1, selected);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Product Deleted", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(MyCart.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Failed to delete product", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is empty", "WARNING", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Select a product", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbDeleteProductMouseClicked

    private void jbDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteProductActionPerformed
        Connection dbconn = dbConnection.connectDb();
        DefaultTableModel delete = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow != -1) {
            String selected = jTable1.getValueAt(selectedRow, 0).toString();
            delete.removeRow(selectedRow);
            String query = "DELETE FROM cart WHERE userId = 1 AND productId = 1";
            try (PreparedStatement statement = dbconn.prepareStatement(query)) {
                statement.setString(1, selected);
                int deleted = statement.executeUpdate();
                System.out.println(deleted);
                JOptionPane.showMessageDialog(this, "Product Deleted", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(MyCart.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Failed to delete product", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is empty", "WARNING", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Select a product", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbDeleteProductActionPerformed

    private void jbDeleteAllProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDeleteAllProductsMouseClicked


    }//GEN-LAST:event_jbDeleteAllProductsMouseClicked

    private void jbDeleteAllProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeleteAllProductsActionPerformed
        // TODO add your handling code here:
        Connection dbconn = dbConnection.connectDb();
        String query = "DELETE FROM cart WHERE userId = 1";
        try (PreparedStatement statement = dbconn.prepareStatement(query)) {

            int deleted = statement.executeUpdate();
            System.out.println(deleted);
            if (deleted > 0) {
                JOptionPane.showMessageDialog(this, "All products are removed", "SUCCESS", HIDE_ON_CLOSE);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete products", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }//GEN-LAST:event_jbDeleteAllProductsActionPerformed

    private void jbShowProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbShowProductsActionPerformed
        String con = "jdbc:mysql://localhost:3306/easylife";
        String username = "root";
        String password = "";
        Statement st = null;
        String requete = "SELECT p.* FROM product p INNER JOIN cart c ON p.productId = c.productId WHERE c.userId = 1";
        try (Connection conn = DriverManager.getConnection(con, username, password)) {
            st = conn.createStatement();
            ResultSet rs = st.executeQuery(requete);
            while (rs.next()) {
                String user1 = rs.getString("productName");
                String brand1 = rs.getString("price");
                String price1 = rs.getString("brand");
                String descr1 = rs.getString("description");

                String dbData[] = {user1, brand1, price1, descr1};
                DefaultTableModel data = (DefaultTableModel) jTable1.getModel();
                data.addRow(dbData);
            }

            conn.close();
        } catch (SQLException e) {
            System.out.println("Error Fetching data: " + e.getMessage());
        }
        jbShowProducts.setEnabled(false);

    }//GEN-LAST:event_jbShowProductsActionPerformed

    private void jbShowProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbShowProductsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbShowProductsMouseClicked

    private void jbAddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAddProductMouseClicked

    }//GEN-LAST:event_jbAddProductMouseClicked

    private void jbAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddProductActionPerformed
        dispose();
        homepage hp = new homepage(userId);
        int usrId = hp.getUserId();
        Main m = new Main(usrId);
        m.setTitle("DashBoard");
        m.setVisible(true);
    }//GEN-LAST:event_jbAddProductActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();

        homepage hp = new homepage(userId);
        hp.setTitle("Home");
        hp.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.Background background1;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAddProduct;
    private javax.swing.JButton jbDeleteAllProducts;
    private javax.swing.JButton jbDeleteProduct;
    private javax.swing.JButton jbShowProducts;
    private javax.swing.JLabel jlabelLoginLogo;
    private com.raven.swing.win_button.WinButton winButton;
    // End of variables declaration//GEN-END:variables
}
