package easylife.EasyLifeUI;

import com.mysql.cj.xdevapi.Statement;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author blessedtasela
 */
public class registerUser extends javax.swing.JFrame {

    /**
     * Creates new form registerUser
     */
    public registerUser() {
        initComponents();
         setBackground(new Color(0,0,0,0));
        init();
    }
     private void init() {
    winButton.initEvent(this, background1);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new com.raven.swing.Background();
        header = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jlabelLoginLogo = new javax.swing.JLabel();
        winButton = new com.raven.swing.win_button.WinButton();
        jPanelFormInput = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        jLabelPasswordLabel1 = new javax.swing.JLabel();
        tfLastname = new javax.swing.JTextField();
        jLabelPasswordLabel2 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabelPasswordLabel3 = new javax.swing.JLabel();
        jLabelPasswordLabel4 = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        jLabelUserLabel1 = new javax.swing.JLabel();
        tfFirstname = new javax.swing.JTextField();
        jLabelPasswordLabel5 = new javax.swing.JLabel();
        jLabelPasswordLabel6 = new javax.swing.JLabel();
        tfPhone = new javax.swing.JTextField();
        tfGender = new javax.swing.JTextField();
        tfCountry = new javax.swing.JTextField();
        jLabelPasswordLabel7 = new javax.swing.JLabel();
        tfState = new javax.swing.JTextField();
        jLabelPasswordLabel9 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        jLabelPasswordLabel11 = new javax.swing.JLabel();
        jButtonRegisterUser = new javax.swing.JButton();
        tfAdress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header.setBackground(new java.awt.Color(29, 101, 166));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 161, 4));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html>  <h1>Register User</h1> </html>");

        jlabelLoginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/easylife/img/EasyLife-logo.jpg"))); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(winButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabelLoginLogo))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addComponent(winButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelLoginLogo)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanelFormInput.setBackground(new java.awt.Color(204, 204, 204));
        jPanelFormInput.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 102, 51))); // NOI18N

        btnRegister.setBackground(new java.awt.Color(204, 204, 255));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(29, 101, 166));
        btnRegister.setText("Register");
        btnRegister.setActionCommand("");
        btnRegister.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabelPasswordLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPasswordLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPasswordLabel1.setText("Last Name");

        tfLastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLastnameActionPerformed(evt);
            }
        });

        jLabelPasswordLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPasswordLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPasswordLabel2.setText("Address");

        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        jLabelPasswordLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPasswordLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPasswordLabel3.setText("E-mail");

        jLabelPasswordLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPasswordLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPasswordLabel4.setText("Password");

        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });

        jLabelUserLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUserLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelUserLabel1.setText("First Name");

        tfFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFirstnameActionPerformed(evt);
            }
        });

        jLabelPasswordLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPasswordLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPasswordLabel5.setText("Gender");

        jLabelPasswordLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPasswordLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPasswordLabel6.setText("Phone");

        tfPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhoneActionPerformed(evt);
            }
        });

        tfGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfGenderActionPerformed(evt);
            }
        });

        tfCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCountryActionPerformed(evt);
            }
        });

        jLabelPasswordLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPasswordLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPasswordLabel7.setText("Country");

        tfState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStateActionPerformed(evt);
            }
        });

        jLabelPasswordLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPasswordLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPasswordLabel9.setText("State");

        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        jLabelPasswordLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPasswordLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPasswordLabel11.setText("User Name");

        jButtonRegisterUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonRegisterUser.setForeground(new java.awt.Color(242, 161, 4));
        jButtonRegisterUser.setText("Back to login");
        jButtonRegisterUser.setToolTipText("");
        jButtonRegisterUser.setActionCommand("Login");
        jButtonRegisterUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormInputLayout = new javax.swing.GroupLayout(jPanelFormInput);
        jPanelFormInput.setLayout(jPanelFormInputLayout);
        jPanelFormInputLayout.setHorizontalGroup(
            jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormInputLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabelPasswordLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPasswordLabel5)
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelFormInputLayout.createSequentialGroup()
                        .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(tfGender, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFormInputLayout.createSequentialGroup()
                        .addGroup(jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFormInputLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(43, 43, 43)
                                .addComponent(jLabelUserLabel1))
                            .addComponent(tfFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormInputLayout.createSequentialGroup()
                                .addComponent(jLabelPasswordLabel1)
                                .addGap(48, 48, 48))
                            .addComponent(tfLastname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tfEmail)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelFormInputLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPasswordLabel4)
                            .addComponent(jLabelPasswordLabel11))
                        .addGap(83, 83, 83)
                        .addGroup(jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfPassword, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanelFormInputLayout.createSequentialGroup()
                        .addComponent(jButtonRegisterUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanelFormInputLayout.createSequentialGroup()
                        .addComponent(tfState, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanelFormInputLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabelPasswordLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPasswordLabel7)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfAdress)
                .addContainerGap())
            .addGroup(jPanelFormInputLayout.createSequentialGroup()
                .addGroup(jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormInputLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabelPasswordLabel2))
                    .addGroup(jPanelFormInputLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabelPasswordLabel3)))
                .addContainerGap())
        );
        jPanelFormInputLayout.setVerticalGroup(
            jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPasswordLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFirstname)
                    .addComponent(tfLastname))
                .addGap(24, 24, 24)
                .addComponent(jLabelPasswordLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPasswordLabel6)
                    .addComponent(jLabelPasswordLabel5))
                .addGap(10, 10, 10)
                .addGroup(jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPhone)
                    .addComponent(tfGender))
                .addGap(15, 15, 15)
                .addGroup(jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPasswordLabel9)
                    .addComponent(jLabelPasswordLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfState)
                    .addComponent(tfCountry))
                .addGap(18, 18, 18)
                .addComponent(jLabelPasswordLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfUsername)
                    .addComponent(jLabelPasswordLabel11))
                .addGap(27, 27, 27)
                .addGroup(jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPassword)
                    .addComponent(jLabelPasswordLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFormInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegisterUser)
                    .addComponent(btnRegister))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanelFormInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanelFormInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterUserActionPerformed
        dispose();
        login loginPage = new login();
        loginPage.setTitle("Login Page");
        loginPage.setVisible(true);
    }//GEN-LAST:event_jButtonRegisterUserActionPerformed

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void tfStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStateActionPerformed

    private void tfCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCountryActionPerformed

    private void tfGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfGenderActionPerformed

    private void tfPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneActionPerformed

    private void tfFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFirstnameActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void tfLastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLastnameActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        String fname = tfFirstname.getText();
        String Lname = tfLastname.getText();
        String gender = tfGender.getText();
        String phone = tfPhone.getText();
        String email = tfEmail.getText();
        String country = tfCountry.getText();
        String state = tfState.getText();
        String Adress = tfAdress.getText();
        String username = tfUsername.getText();
        String password = tfPassword.getText();

        if (fname.isEmpty() || Lname.isEmpty() || gender.isEmpty() || phone.isEmpty() || email.isEmpty() || country.isEmpty() || state.isEmpty() || Adress.isEmpty() || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill up the from properly.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            registerUser(fname, Lname, gender, phone, email, country, state,Adress , username, password);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.Background background1;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButtonRegisterUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelPasswordLabel1;
    private javax.swing.JLabel jLabelPasswordLabel11;
    private javax.swing.JLabel jLabelPasswordLabel2;
    private javax.swing.JLabel jLabelPasswordLabel3;
    private javax.swing.JLabel jLabelPasswordLabel4;
    private javax.swing.JLabel jLabelPasswordLabel5;
    private javax.swing.JLabel jLabelPasswordLabel6;
    private javax.swing.JLabel jLabelPasswordLabel7;
    private javax.swing.JLabel jLabelPasswordLabel9;
    private javax.swing.JLabel jLabelUserLabel1;
    private javax.swing.JPanel jPanelFormInput;
    private javax.swing.JLabel jlabelLoginLogo;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfCountry;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFirstname;
    private javax.swing.JTextField tfGender;
    private javax.swing.JTextField tfLastname;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfState;
    private javax.swing.JTextField tfUsername;
    private com.raven.swing.win_button.WinButton winButton;
    // End of variables declaration//GEN-END:variables

    private void registerUser(String fname, String Lname, String gender, String phone, String email, String country, String state, String adress, String username, String password) {
        Connection dbconn = dbConnection.connectDb();
        if (dbconn != null) {
            try {
                String insertCustomer = "INSERT INTO customer(firstName,"
                        + "lastName,"
                        + "gender,"
                        + "phone,"
                        + "email,"
                        + "country,"
                        + "state,"
                        + "address)"
                        + " VALUES (?,?,?,?,?,?,?,?)";

                String insertLogin = "INSERT INTO login(customerId,"
                        + " username,"
                        + " password)"
                        + " VALUES (?,?,?)";

                PreparedStatement customerStatement = dbconn.prepareStatement(insertCustomer, PreparedStatement.RETURN_GENERATED_KEYS);
                PreparedStatement loginStatement = dbconn.prepareStatement(insertLogin, PreparedStatement.RETURN_GENERATED_KEYS);

                customerStatement.setString(1, fname);
                customerStatement.setString(2, Lname);
                customerStatement.setString(3, gender);
                customerStatement.setString(4, phone);
                customerStatement.setString(5, email);
                customerStatement.setString(6, country);
                customerStatement.setString(7, state);
                customerStatement.setString(8, adress);

                // Execute the customer insert statement and retrieve the generated keys
                customerStatement.executeUpdate();
                ResultSet generatedKeys = customerStatement.getGeneratedKeys();

                // Check if any keys were generated
                if (generatedKeys.next()) {
                    // Retrieve the generated customerId
                    int customerId = generatedKeys.getInt(1);

                    // Use the generated customerId in the login insert statement
                    loginStatement.setInt(1, customerId);
                    loginStatement.setString(2, username);
                    loginStatement.setString(3, password);
                    // Execute the login insert statement
                    loginStatement.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Account created successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    login loginPage = new login();
                    loginPage.setTitle("Login Page");
                    loginPage.setVisible(true);
                } else {
                    // Handle the case where no keys were generated
                    JOptionPane.showMessageDialog(this, "Failed to retrieve customer ID", "Error", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Error creating account. please try again", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            System.out.println("The connection not available.");
        }
    }

}
